version: '3.8'

services:
  python-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db-hw02

  postgres-db-hw02:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"